### ISSUE TITLE
Possible enhancement: @zipper

### ISSUE THREAD

**Issue by mfalda** [bunbun/ruffus#62]
I am trying to use Ruffus for a customized Proteomics pipeline and I found an interesting case that could be missing (or that I am not able to implement): Multiple technical replicates of the same sample should be aligned on the retention times / masses, for example using [this tool](http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/html/TOPP_MapAlignerPoseClustering.html). To do this they have to be processed together and then the same input files, corrected, will be given in output.
I think that it could be possible to generate dynamically those sets and then `transform` them, however I think also that it could be useful to have a new operator analogous to the Python "zip" function. The `zip`ped task would produce a set of output files that will be added to its "dependency list", in such a way that modifying a single output file in the set will induce the rebuilding of the whole set. It is a sort of combination of `collate` and `split`, a paired "many to many" operator.

As an example (no speculations on biological correctness of the procedure...), if I want to align "sample1_tech1_control.idXML", "sample1_tech2_control.idXML" and "sample1_tech3_control.idXML"
with "sample1_tech1_treated.idXML", "sample1_tech2_treated.idXML" and"sample1_tech3_treated.idXML" respectively and produce in output other six aligned versions of each input file I would use a task like the following:

```Python
@zip([stepX],
     formatter("\w+\.(?P<experiment>sample\d+)[^.]+\.idXML"), # collate filter 
    ...) # replacements
def stepY(input_files, output_files):
 
    # here the tool can access the whole set of the collated input files
    # [input_file[0], input_file[1], ...] -> [output_file[0], output_file[1], ...]

# end def stepY
```

**Comment by bunbun** [comment]
Dear Marco,
I am afraid I don't quite understand what `＠zip` is supposed to do.
Could you perhaps sketch out a bit more what sort of inputs and outputs it creates.

I am guessing that [stepX] is a list of (e.g. 6) files or for example a @transform tasks with (e.g. 6) jobs.
```python
stepX = [ "sample1_tech1_control.idXML", "sample1_tech2_control.idXML",
          "sample1_tech3_control.idXML", "sample1_tech1_treated.idXML",
          "sample1_tech2_treated.idXML", "sample1_tech3_treated.idXML"]
```
or is stepX just the first three ``"*_control.idXML"`` files


##  ``add_inputs``
You would like ``stepY`` to be fed all six files? Usually people require three jobs each with a pair of files.
In other words, 3 invocations of ``stepY()`` where for each job  
```python
    input_files = [ "sample1_tech1_control.idXML",  "sample1_tech1_treated.idXML"]
    input_files = [ "sample1_tech2_control.idXML",  "sample1_tech2_treated.idXML"]
    input_files = [ "sample1_tech3_control.idXML",  "sample1_tech3_treated.idXML"]
```

In which case, you would need:
```python
@transform([stepX], 
          formatter("(\w+)(?P<experiment>sample\d+)(?P<tech>tech\d+)_control\.idXML"),
          add_inputs("\1\g<experiment>\g<tech>_treated.idXML"),
          ...)#replacements
def stepY(input_file_pair, output_files):
           pass
```

## ``@zip``
Am I right in thinking you want to generate all the ``"treated.id"`` files as input given your set of ``"control.id"`` files. 
``add_inputs()`` and ``formatter()`` can do this if you know how many (``"control.id"``) files there are but you would like the substitutions to be generated dynamically.


Have I misunderstood you?


If I haven't, the general Ruffus principle applies:
If this is a matter of general utility I am willing to do the extra work. Otherwise if this is a corner case, it will further overload / complicate the syntax of the whole library. You might need to have recourse to generating parameters on the fly (see the [manual page] (http://www.ruffus.org.uk/tutorials/new_tutorial/onthefly.html#new-manual-on-the-fly))

Leo

**Comment by mfalda** [comment]
Dear Leo, 
   thank you for considering my idea and sorry for my confused post. I am still learning, but I think I have solved (I was performing some other final tests before writing again here).  I try to simplify: Suppose I want to take two kinds of files ".tsv1" and ".tsv2" from a directory "step4a", process them together and then output two other files aligned in the directory "step5"; currently I have done in this way:

```Python
# this function creates pairs of files to be processed together
@transform([step34a], # previous step
           formatter("\w+.(?P<name>\w+)(?P<num>\d+)(?P<num1>\w+)\.tsv1"), # filter
           ["step4a/{name[0]}{num[0]}{num1[0]}.tsv1", "step4a/{name[0]}{num[0]}{num1[0]}.tsv2"]) # replacement
def pair_step45(inputs, outputs):

   print inputs + ' -> ' + outputs

# end def pair_step45


# 2 inputs -> 2 outputs: process files *.tsv1 and *.tsv2 together from the directory step4a and outputs two aligned files to the directory step5
@follows(pair_step45, mkdir("step5")) # first I have to pair files together (is this a duplicated requirement? (see the line below))
@transform(pair_step45,
           formatter("(?P<name>\w+).tsv"), # filter
           ["step5/aligned_{name[0]}.tsv1", "step5/aligned_{name[0]}.tsv2"]) # replacement
def step45(input_files, output_files):
   
    print "Processing %s + %s" % (input_files[0], input_files[1])
    ii = open(input_files[0])
    ii = open(input_files[1])
    print "Producing %s + %s" % (output_files[0], output_files[1])
    oo = open(output_files[0], "w")
    oo = open(output_files[1], "w")
    
# end def step45
```

Ruffus output is, correctly:
```
Task enters queue = 'step45' 
    Job  = [[step4a/step1a.tsv1, step4a/step1a.tsv2] -> [step5/aligned_step1a.tsv1, step5/aligned_step1a.tsv2]] ...
        Missing files [step5/aligned_step1a.tsv1, step5/aligned_step1a.tsv2] 
    Job  = [[step4a/step1b.tsv1, step4a/step1b.tsv2] -> [step5/aligned_step1b.tsv1, step5/aligned_step1b.tsv2]] ...
        Missing files [step5/aligned_step1b.tsv1, step5/aligned_step1b.tsv2] 
    Job  = [[step4a/step1c.tsv1, step4a/step1c.tsv2] -> [step5/aligned_step1c.tsv1, step5/aligned_step1c.tsv2]] ...
        Missing files [step5/aligned_step1c.tsv1, step5/aligned_step1c.tsv2] 
    Job  = [[step4a/step1a.tsv1, step4a/step1a.tsv2] -> [step5/aligned_step1a.tsv1, step5/aligned_step1a.tsv2]] completed
    Job  = [[step4a/step1b.tsv1, step4a/step1b.tsv2] -> [step5/aligned_step1b.tsv1, step5/aligned_step1b.tsv2]] completed
    Job  = [[step4a/step1c.tsv1, step4a/step1c.tsv2] -> [step5/aligned_step1c.tsv1, step5/aligned_step1c.tsv2]] completed
Completed Task = 'step45' 
```

It seemed to me that such an operator could be similar to `zip`:
```Python
>>> tsv1 = ["step4a/step1a.tsv1", "step4a/step1b.tsv1", "step4a/step1c.tsv1"]
>>> tsv2 = ["step4a/step1a.tsv2", "step4a/step1b.tsv2", "step4a/step1c.tsv2"]
>>> zip(tsv1, tsv2)
[('step4a/step1a.tsv1', 'step4a/step1a.tsv2'),
 ('step4a/step1b.tsv1', 'step4a/step1b.tsv2'),
 ('step4a/step1c.tsv1', 'step4a/step1c.tsv2')]
```

If you think that this could be an enrichment of Ruffus operators you could add @zip, otherwise close my request without problems.
Thanks,

       Marco

**Comment by bunbun** [comment]
Dear Marco,
I am beginning to see what you mean. If I haven't misunderstood you, you would like to omit ``pair_step45()`` whose sole purpose in life is to make sure that the ``tsv1`` and ``tsv2`` files travel through the pipeline together. 

Sometimes, it is clearest to have a separate step like this, but, in this case, you should be able to get away with just forwarding the (grouped/paired) input files, so that the input and output files are identical:

```python
@transform([step34a], # previous step
           formatter("(\w+.)(?P<name>\w+)(?P<num>\d+)(?P<num1>\w+)\.tsv1"), # filter
           [r"\1/{name[0]}{num[0]}{num1[0]}.tsv1", r"\1/{name[0]}{num[0]}{num1[0]}.tsv2"]) # forward
def pair_step45(inputs, outputs):
   print inputs + ' -> ' + outputs
```

Otherwise, you would have to either make a copy or a soft link to the files.

Otherwise, you can skip the entire step by using ``add_inputs``:

```python
# @follows is redundant
@mkdir("step5")
@transform(step34a,
           formatter("(\w+.)(?P<name>\w+)(?P<num>\d+)(?P<num1>\w+)\.tsv1"), # filter
           # add the tsv2 as an input to this task as well
           add_inputs(r"\1{name[0]}{num[0]}{num1[0]}.tsv2"),
           ["step5/aligned_{name[0]}.tsv1", 
            "step5/aligned_{name[0]}.tsv2"]) # replacement
def step45(input_files, output_files):

    print "Processing %s + %s" % (input_files[0], input_files[1])
    ii = open(input_files[0])
    ii = open(input_files[1])
    print "Producing %s + %s" % (output_files[0], output_files[1])
    oo = open(output_files[0], "w")
    oo = open(output_files[1], "w")
```

This is untested (buggy!) code off the top of my head.

The reason why there is no "@zip" decorator is that jobs / ruffus output are not completed/retired in the original order. I could try to maintain the order of files by secretly tagging jobs as they pass through the pipeline but I haven't done so (yet).

Hope this helps

Leo

**Comment by mfalda** [comment]
Dear Leo,
yes, now you have understood correctly: I was looking for a way to simplify my code and I though that a syntax like the following could be simpler:

```Python
@mkdir("step5")
@zip(step45,
    [["step4a/*.tsv1"], ["step4a/*.tsv2"], ...], 
    [suffix(".tsv1"), suffix(".tsv2"), ...')],
    [".tsv1", ".tsv2", ...], # or using a list of formatters
    output_dir = "step5")
def step45(input_files, output_files):

    print "Processing %s + %s + ..." % (input_files[0], input_files[1], ...)
    map(lambda input_file: open(input_file), input_files)

    # process all input files together

    print "Producing %s + %s + ..." % (output_files[0], output_files[1] ...)
    map(lambda output_file: open(output_file, 'w'), output_files)

# end def step45

```

I close this issue since it is clear that Ruffus is already enough powerful.
Thank you for having created such an useful tool!
Best regards,

Marco

**Comment by mfalda** [comment]
Errata corrige:

```Python
@mkdir("step5")
@zip([["step4a/*.tsv1"], ["step4a/*.tsv2"], ...], # <= I left a spurious "step45"
    [suffix(".tsv1"), suffix(".tsv2"), ...')],
    [".tsv1", ".tsv2", ...], # or using a list of formatters
    output_dir = "step5")
def step45(input_files, output_files):

    print "Processing %s + %s + ..." % (input_files[0], input_files[1], ...)
    map(lambda input_file: open(input_file), input_files)

    # process all input files together

    print "Producing %s + %s + ..." % (output_files[0], output_files[1] ...)
    map(lambda output_file: open(output_file, 'w'), output_files)

# end def step45
```

**Comment by bunbun** [comment]
Thank you very much
